spring.application.name=htaproject2308

#Mybatis
mybatis.mapper-locations=mapper/**/*.xml

logging.level.com.example.performancecache.mapper=TRACE

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.master.driver-class-name=org.h2.Driver
spring.datasource.master.jdbc-url=jdbc:h2:mem:testdb;MODE=MYSQL
spring.datasource.master.username=sa
spring.datasource.master.password=

# Resilience4j Circuit Breaker ??
resilience4j.circuitbreaker.instances.myCircuitBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.myCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.myCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.myCircuitBreaker.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.myCircuitBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.myCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.myCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true

# Actuator ????? ??
management.endpoints.web.exposure.include=health,info
