DROP TABLE IF EXISTS notice;

CREATE TABLE notice(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(30),
    content VARCHAR(100),
    who VARCHAR(30),
    views INT DEFAULT 0,
    createDate TIMESTAMP NOT NULL,
    updateDate TIMESTAMP NOT NULL
);

CREATE TABLE book (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  author VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
